name: ksu_waitsys

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: KernelSU2/waitsys

      - name: ninja
        run: sudo apt-get update && sudo apt-get install -y ninja-build

      - name: grab ndk
        run: |
          curl -L https://dl.google.com/android/repository/android-ndk-r23b-linux.zip -o ndk-linux.zip
          unzip ndk-linux.zip > /dev/null 2>&1

      - name: compile via ndk
        run: |
          pwd
          mkdir binaries
          
          NDK_PATH="$PWD/android-ndk-r23b"
          cmake -B build -G Ninja -DCMAKE_TOOLCHAIN_FILE=$NDK_PATH/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-21 -DANDROID_STL=c++_static -DCMAKE_BUILD_TYPE=Release

          cmake --build build
          
          $NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip build/waitsys
          cp build/waitsys binaries/waitsys_arm32
          ls -lh binaries/
          file binaries/*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: binaries/


