name: tinyfs_su

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: grab ndk
        run: |
          curl -L https://dl.google.com/android/repository/android-ndk-r30-beta2-linux.zip -o ndk-linux.zip
          unzip ndk-linux.zip > /dev/null 2>&1

      - name: compile via ndk
        run: |
          pwd
          mkdir binaries

          ./android-ndk-r30-beta2/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang -Oz -s -Wl,--gc-sections,--strip-all,-z,norelro -fno-unwind-tables -Wl,--entry=__start -flto -fmerge-all-constants -static -nostartfiles -ffreestanding kernelsu/tinyfs_su/su.c -o binaries/tinysu_bare
          ./android-ndk-r30-beta2/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang -Oz -s -Wl,--gc-sections,--strip-all,-z,norelro -fno-unwind-tables kernelsu/tinyfs_su/su-ndk.c -o binaries/tinysu_dynamic
          wc -c binaries/*
          file binaries/*

          for file in binaries/*; do ./android-ndk-r30-beta2/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip $file ; done
          wc -c binaries/*
          file binaries/*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: binaries/


